---
date-modified: "today"
format: 
  html:
    link-external-newwindow: true
    page-layout: full
    toc: false
editor_options: 
  chunk_output_type: console
---

# Course information

We will be working off [these R tutorials](https://ohsuitg-my.sharepoint.com/:f:/g/personal/wakim_ohsu_edu/EhTBEvNn3MZHvD0NfnARUR4BleqEPYWy2nxRKI17tij2dw?e=vYnQtD) from my Epi 525 class

# Schedule

| Week | Date | Lesson | Topic | Video | Slides QMD | Slides PDF | Slides Notes | Activity |
|-------|-------|---------|--------------|:-----:|:----:|:----:|:----:|:-----:|
| 1 | 7/9 | R01 | Download R and RStudio |  | [[{{< iconify ri slideshow-fill size=30px >}}](/lessons/R01_Download_R/R01_Download_R.qmd)]{style="color:#f8f5f0;"} | [[{{< iconify bi file-earmark-pdf-fill size=28px >}}](/lessons/R01_Download_R/R01_Download_R.pdf)]{style="color:#f8f5f0;"} |  |  |
|  |  | R02 | R Basics, part 1 |  | [[{{< iconify ri slideshow-fill size=30px >}}](lessons/R02_Basics_01/R02_Basics_01.qmd)]{style="color:#f8f5f0;"} | [[{{< iconify bi file-earmark-pdf-fill size=28px >}}](lessons/R02_Basics_01/R02_Basics_01.pdf)]{style="color:#f8f5f0;"} | [[{{< iconify pepicons-pop pen-circle-filled size=29px >}}](lessons/R02_Basics_01/R02_Basics_01_work.R)]{style="color:#f8f5f0;"} |  |
| 2 | 7/16 | R03 | R Basics, part 2 |  | [[{{< iconify ri slideshow-fill size=30px >}}](lessons/R03_Basics_02/R03_Basics_02.qmd)]{style="color:#f8f5f0;"} | [[{{< iconify bi file-earmark-pdf-fill size=28px >}}](lessons/R03_Basics_02/R03_Basics_02.pdf)]{style="color:#f8f5f0;"} | [[{{< iconify pepicons-pop pen-circle-filled size=29px >}}](lessons/R03_Basics_02/R03_Basics_02_work.R)]{style="color:#f8f5f0;"} |  |
| 3 | 7/23 | R04 | Reproducibility, File Organization, and Projects |  | [[{{< iconify ri slideshow-fill size=30px >}}](lessons/R04_Reproducibility/R04_Reproducibility.qmd)]{style="color:#f8f5f0;"} | [[{{< iconify bi file-earmark-pdf-fill size=28px >}}](lessons/R04_Reproducibility/R04_Reproducibility.pdf)]{style="color:#f8f5f0;"} | [{{< iconify pepicons-pop pen-circle-filled size=29px >}}]{style="color:#f8f5f0;"} |  |
| 4 | 7/30 | R05 | Intro to Quarto, packages, and importing data |  | [[{{< iconify ri slideshow-fill size=30px >}}](lessons/R05_Quarto_01/R05_Quarto_01.qmd)]{style="color:#f8f5f0;"} | [[{{< iconify bi file-earmark-pdf-fill size=28px >}}](lessons/R05_Quarto_01/R05_Quarto_01.pdf)]{style="color:#f8f5f0;"} | [{{< iconify pepicons-pop pen-circle-filled size=29px >}}]{style="color:#f8f5f0;"} |  |
| 5 | 8/6 | R06 | `ggplot` , part 1 |  | [[{{< iconify ri slideshow-fill size=30px >}}](lessons/R06_ggplot_01/R06_ggplot_01.qmd)]{style="color:#f8f5f0;"} | [[{{< iconify bi file-earmark-pdf-fill size=28px >}}](lessons/R06_ggplot_01/R06_ggplot_01.pdf)]{style="color:#f8f5f0;"} | [{{< iconify pepicons-pop pen-circle-filled size=29px >}}]{style="color:#f8f5f0;"} |  |
| 6 | 8/13 | R07 | LaTeX in Quarto |  | [[{{< iconify ri slideshow-fill size=30px >}}](lessons/R07_LaTeX/R07_LaTeX.qmd)]{style="color:#f8f5f0;"} | [[{{< iconify bi file-earmark-pdf-fill size=28px >}}](lessons/R07_LaTeX/R07_LaTeX.pdf)]{style="color:#f8f5f0;"} | [{{< iconify pepicons-pop pen-circle-filled size=29px >}}]{style="color:#f8f5f0;"} |  |
| 7 | 8/20 | R08 | Transforming and subetting data with `tidyverse` |  | [[{{< iconify ri slideshow-fill size=30px >}}](lessons/R08_tidyverse_01/R08_tidyverse_01.qmd)]{style="color:#f8f5f0;"} | [[{{< iconify bi file-earmark-pdf-fill size=28px >}}](lessons/R08_tidyverse_01/R08_tidyverse_01.pdf)]{style="color:#f8f5f0;"} | [[{{< iconify pepicons-pop pen-circle-filled size=29px >}}](lessons/R08_tidyverse_01/R08_tidyverse_01_notes.pdf) [{{< iconify pepicons-pop pen-circle-filled size=29px >}}](lessons/R08_tidyverse_01/R08_tidyverse_01_notes.qmd)]{style="color:#f8f5f0;"} |  |
| 8 | 8/27 | R09 | Summarizing data with `tidyverse` and Table 1 |  | [[{{< iconify ri slideshow-fill size=30px >}}](lessons/R09_tidyverse_02/R09_tidyverse_02.qmd)]{style="color:#f8f5f0;"} | [[{{< iconify bi file-earmark-pdf-fill size=28px >}}](lessons/R09_tidyverse_02/R09_tidyverse_02.pdf)]{style="color:#f8f5f0;"} | [[{{< iconify pepicons-pop pen-circle-filled size=29px >}}](lessons/R09_tidyverse_02/R09_tidyverse_02_notes.pdf)]{style="color:#f8f5f0;"} |  |
| 9 | 9/3 | VPT 627 |  |  |  |  |  |  |

: {.striped .hover tbl-colwidths="\[4, 6, 6, 15, 6,6, 6, 6\]"}
